[package]
name = "hal2"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
bitfrob = "1.0.0"
paste = "1.0.12"
rand_core = { version = "0.6.4", default-features = false, optional = true }
vm-types = { version = "0.1.0", path = "../vm-types" }

[features]
default = ["rand_core"]
