[package]
name = "staid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lagrange = { version = "0.1.0", path = "../lagrange" }
lock_api = "0.4.9"
