[package]
name = "pci-x86"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal-x86_64 = { version = "0.1.0", path = "../hal-x86_64" }
pci-types = { version = "0.1.0", path = "../pci-types" }
