[package]
name = "holo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hal = { version = "0.1.0", path = "../hal" }
hal-core = { version = "0.1.0", path = "../hal-core" }
spin = "0.9.5"
